### ISSUE TITLE
Hey, I'm making a website

### ISSUE THREAD

**Issue by Tmktahu** [mikeshardmind/wakfu-utils#1]
Hey I attempted to find you on Discord, but wasn't able to. Not sure if the username you have in the README is correct.

Either way, I also recently started up a Wakfu project and was curious if you'd be interested in joining in. I'm making a character builder that currently operates off data saved locally in the user's browser, and JSON files. I've got the github page here: https://github.com/Tmktahu/wakforge and you can find the site live at https://wakforge.org/ if you want to see how it's going.

I've been working with the guys in the group Epitaph, as I plan on playing the mono server with them. Here's an invite to the discord server if you're interested: https://discord.gg/dv4CaAcb

**Comment by Tmktahu** [comment]
oh and my Discord username is 'fryke' if you'd prefer to just DM. forgot that part

**Comment by mikeshardmind** [comment]
I should probably update the readme to clarify that that's a discord invite code not a username, but I'd be happy to collaborate. I still intend to keep this as its own separate tool, but I can do what I can to make sure it's usable by wakforge in the future if you'd like to be able to recommend sets to users based on the output of this.
