### ISSUE TITLE
Composable filtering and ensuring this is maintainable long term.

### ISSUE THREAD

**Issue by mikeshardmind** [mikeshardmind/wakfu-utils#2]
Absent any bugs in the existing implementation or anything reasonably worth rushing in, I'm going to be taking time to restructure the internals of the solver slightly.

Accept Solver Parameters-> Generate {item filters/conditions, set conditions} -> Filter items -> Filter sets from permuted items.

This is already what's being done, but I'd like to take the time to more explicitly split these steps and have the filters be made composable with each other to allow an easier-to-{read, maintain, extend} solver.

**Comment by DiscordLiz** [comment]
Can I be the devil on your shoulder and remind you that this also will make it easier to just write it in Haskell to get more performance?

**Comment by mikeshardmind** [comment]
handled, for now.
